export const viewsResponse = {
  preferenceDetails: [
    {
      id: 'RETAIL_ENQUIRY',
      name: 'View 1',
      active: false,
      shareable: false,
      detail: {
        filterState: {},
        colState: [
          {
            hide: false,
            pinned: 'right',
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 56,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'kabab',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: 'asc',
            pivotIndex: null,
            colId: 'itemNbr',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'itemDesc',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'category',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'subCategory',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: 'asc',
            pivotIndex: null,
            colId: 'clubNbr',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'retailAmount',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'effectiveDate',
            rowGroup: false
          },
          {
            hide: true,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 200,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'retailReason',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'retailReasonCodeTxt',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'status',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'type',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'regionName',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'marketAreaNumber',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'stateProvCode',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'orderableCost',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'orderableQty',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'whpkSellAmt',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'margin',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'onHandQty',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'onOrderQty',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'claimOnHandQty',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'totalSales',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'totalCost',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'totalUnits',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'outOfStockDate',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'itemStatus',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'itemOnShelfDate',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'itemOffShelfDate',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'piMarket',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'piMarketType',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'piItem',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'creatorId',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'createTimestamp',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'lastChangeId',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'lastChangedTimestamp',
            rowGroup: false
          },
          {
            hide: true,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 200,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'blockData',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'lock',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'blockReasonCodeTxt',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'lastChangeTimeStamp',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'startDate',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'endDate',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'costcoAmount',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'costcoDate',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'bjsAmount',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'bjsDate',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'costcoMintAmount',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'costcoMintDate',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'amazonMintAmount',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'amazonMintDate',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'walmartMintAmount',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'walmartMintDate',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'bestBuyMintAmount',
            rowGroup: false
          },
          {
            hide: false,
            pinned: null,
            rowGroupIndex: null,
            sortIndex: null,
            flex: null,
            width: 130,
            aggFunc: null,
            pivot: false,
            sort: null,
            pivotIndex: null,
            colId: 'bestBuyMintDate',
            rowGroup: false
          }
        ]
      }
    }
  ]
};
